# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TM.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(737, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LaserControlBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LaserControlBox.setGeometry(QtCore.QRect(290, 180, 331, 211))
        self.LaserControlBox.setFlat(False)
        self.LaserControlBox.setCheckable(False)
        self.LaserControlBox.setObjectName("LaserControlBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.LaserControlBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 19, 291, 193))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.LaserControlLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.LaserControlLayout.setContentsMargins(0, 0, 0, 0)
        self.LaserControlLayout.setObjectName("LaserControlLayout")
        self.StartStopButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.StartStopButton.setObjectName("StartStopButton")
        self.LaserControlLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.StartStopButton)
        self.FileBox = QtWidgets.QPushButton(self.formLayoutWidget)
        self.FileBox.setObjectName("FileBox")
        self.LaserControlLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.FileBox)
        self.StretchButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.StretchButton.setObjectName("StretchButton")
        self.LaserControlLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.StretchButton)
        self.NumberOfCyclesLayout = QtWidgets.QHBoxLayout()
        self.NumberOfCyclesLayout.setObjectName("NumberOfCyclesLayout")
        self.NumberOfCyclesLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.NumberOfCyclesLabel.setObjectName("NumberOfCyclesLabel")
        self.NumberOfCyclesLayout.addWidget(self.NumberOfCyclesLabel)
        self.NumberOfCyclesField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.NumberOfCyclesField.setObjectName("NumberOfCyclesField")
        self.NumberOfCyclesLayout.addWidget(self.NumberOfCyclesField)
        self.LaserControlLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.NumberOfCyclesLayout)
        self.NumberOfCycleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.NumberOfCycleLabel.setObjectName("NumberOfCycleLabel")
        self.LaserControlLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.NumberOfCycleLabel)
        self.NumberOfCycleField = QtWidgets.QLabel(self.formLayoutWidget)
        self.NumberOfCycleField.setText("")
        self.NumberOfCycleField.setObjectName("NumberOfCycleField")
        self.LaserControlLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.NumberOfCycleField)
        self.SetToTenButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.SetToTenButton.setObjectName("SetToTenButton")
        self.LaserControlLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.SetToTenButton)
        self.MoveOutButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.MoveOutButton.setObjectName("MoveOutButton")
        self.LaserControlLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.MoveOutButton)
        self.StagesConrtolBox = QtWidgets.QGroupBox(self.centralwidget)
        self.StagesConrtolBox.setGeometry(QtCore.QRect(50, 170, 211, 241))
        self.StagesConrtolBox.setObjectName("StagesConrtolBox")
        self.MoveLeftStageLeftButton = QtWidgets.QPushButton(self.StagesConrtolBox)
        self.MoveLeftStageLeftButton.setGeometry(QtCore.QRect(3, 160, 70, 23))
        self.MoveLeftStageLeftButton.setObjectName("MoveLeftStageLeftButton")
        self.MoveLeftStageRightButton = QtWidgets.QPushButton(self.StagesConrtolBox)
        self.MoveLeftStageRightButton.setGeometry(QtCore.QRect(79, 160, 69, 23))
        self.MoveLeftStageRightButton.setObjectName("MoveLeftStageRightButton")
        self.MoveRightStageLeftButton = QtWidgets.QPushButton(self.StagesConrtolBox)
        self.MoveRightStageLeftButton.setGeometry(QtCore.QRect(2, 210, 71, 23))
        self.MoveRightStageLeftButton.setObjectName("MoveRightStageLeftButton")
        self.MoveRightStageRightButton = QtWidgets.QPushButton(self.StagesConrtolBox)
        self.MoveRightStageRightButton.setGeometry(QtCore.QRect(79, 210, 70, 23))
        self.MoveRightStageRightButton.setObjectName("MoveRightStageRightButton")
        self.MoveRightStageField = QtWidgets.QLineEdit(self.StagesConrtolBox)
        self.MoveRightStageField.setGeometry(QtCore.QRect(155, 210, 54, 20))
        self.MoveRightStageField.setObjectName("MoveRightStageField")
        self.NumberOfCycleLabel_2 = QtWidgets.QLabel(self.StagesConrtolBox)
        self.NumberOfCycleLabel_2.setGeometry(QtCore.QRect(10, 140, 81, 13))
        self.NumberOfCycleLabel_2.setObjectName("NumberOfCycleLabel_2")
        self.NumberOfCycleLabel_3 = QtWidgets.QLabel(self.StagesConrtolBox)
        self.NumberOfCycleLabel_3.setGeometry(QtCore.QRect(10, 190, 81, 13))
        self.NumberOfCycleLabel_3.setObjectName("NumberOfCycleLabel_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.StagesConrtolBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(2, 22, 207, 100))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.StagesLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.StagesLayout.setContentsMargins(0, 0, 0, 0)
        self.StagesLayout.setObjectName("StagesLayout")
        self.StagesToHomeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.StagesToHomeButton.setObjectName("StagesToHomeButton")
        self.StagesLayout.addWidget(self.StagesToHomeButton, 1, 0, 1, 2)
        self.StagesToZerosButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.StagesToZerosButton.setObjectName("StagesToZerosButton")
        self.StagesLayout.addWidget(self.StagesToZerosButton, 0, 0, 1, 2)
        self.MoveStagesButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.MoveStagesButton.setObjectName("MoveStagesButton")
        self.StagesLayout.addWidget(self.MoveStagesButton, 2, 0, 1, 1)
        self.MoveStagesField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.MoveStagesField.setObjectName("MoveStagesField")
        self.StagesLayout.addWidget(self.MoveStagesField, 2, 1, 1, 1)
        self.MoveLeftStageField = QtWidgets.QLineEdit(self.StagesConrtolBox)
        self.MoveLeftStageField.setGeometry(QtCore.QRect(154, 160, 54, 20))
        self.MoveLeftStageField.setObjectName("MoveLeftStageField")
        self.LogBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LogBox.setGeometry(QtCore.QRect(280, 50, 331, 101))
        self.LogBox.setObjectName("LogBox")
        self.LogField = QtWidgets.QTextBrowser(self.LogBox)
        self.LogField.setGeometry(QtCore.QRect(10, 20, 311, 71))
        self.LogField.setObjectName("LogField")
        self.ConnectionBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ConnectionBox.setGeometry(QtCore.QRect(50, 30, 211, 121))
        self.ConnectionBox.setObjectName("ConnectionBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.ConnectionBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 19, 191, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ConnectionLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ConnectionLayout.setContentsMargins(0, 0, 0, 0)
        self.ConnectionLayout.setObjectName("ConnectionLayout")
        self.AutoDetectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.AutoDetectButton.setEnabled(True)
        self.AutoDetectButton.setObjectName("AutoDetectButton")
        self.ConnectionLayout.addWidget(self.AutoDetectButton)
        self.ManualConnectionLayout = QtWidgets.QFormLayout()
        self.ManualConnectionLayout.setVerticalSpacing(6)
        self.ManualConnectionLayout.setObjectName("ManualConnectionLayout")
        self.manualConnectionBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.manualConnectionBox.setChecked(False)
        self.manualConnectionBox.setObjectName("manualConnectionBox")
        self.ManualConnectionLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.manualConnectionBox)
        self.laserPortLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.laserPortLabel.setObjectName("laserPortLabel")
        self.ManualConnectionLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.laserPortLabel)
        self.laserPortLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.laserPortLineEdit.setEnabled(True)
        self.laserPortLineEdit.setClearButtonEnabled(False)
        self.laserPortLineEdit.setObjectName("laserPortLineEdit")
        self.ManualConnectionLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.laserPortLineEdit)
        self.shutterPortLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.shutterPortLabel.setObjectName("shutterPortLabel")
        self.ManualConnectionLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.shutterPortLabel)
        self.shutterPortLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.shutterPortLineEdit.setEnabled(True)
        self.shutterPortLineEdit.setObjectName("shutterPortLineEdit")
        self.ManualConnectionLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.shutterPortLineEdit)
        self.manualConnectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.manualConnectButton.setObjectName("manualConnectButton")
        self.ManualConnectionLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.manualConnectButton)
        self.ConnectionLayout.addLayout(self.ManualConnectionLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 737, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Taper Making UI v.2 .12(01.06.2021)"))
        self.LaserControlBox.setTitle(_translate("MainWindow", "Taping controll"))
        self.StartStopButton.setText(_translate("MainWindow", "Start/stop"))
        self.FileBox.setText(_translate("MainWindow", "Please select file"))
        self.StretchButton.setText(_translate("MainWindow", "Stretch"))
        self.NumberOfCyclesLabel.setText(_translate("MainWindow", "Total number of cycles:"))
        self.NumberOfCyclesField.setText(_translate("MainWindow", "19"))
        self.NumberOfCycleLabel.setText(_translate("MainWindow", "Number of cylce:"))
        self.SetToTenButton.setText(_translate("MainWindow", "Set to 10%"))
        self.MoveOutButton.setText(_translate("MainWindow", "Move out"))
        self.StagesConrtolBox.setTitle(_translate("MainWindow", "Stages controll"))
        self.MoveLeftStageLeftButton.setText(_translate("MainWindow", "<-"))
        self.MoveLeftStageRightButton.setText(_translate("MainWindow", "->"))
        self.MoveRightStageLeftButton.setText(_translate("MainWindow", "<-"))
        self.MoveRightStageRightButton.setText(_translate("MainWindow", "->"))
        self.MoveRightStageField.setText(_translate("MainWindow", "0.05"))
        self.NumberOfCycleLabel_2.setText(_translate("MainWindow", "Left stage"))
        self.NumberOfCycleLabel_3.setText(_translate("MainWindow", "Right stage"))
        self.StagesToHomeButton.setText(_translate("MainWindow", "Stages to home"))
        self.StagesToZerosButton.setText(_translate("MainWindow", "Stages to zeros"))
        self.MoveStagesButton.setText(_translate("MainWindow", "Move stages"))
        self.MoveLeftStageField.setText(_translate("MainWindow", "0.05"))
        self.LogBox.setTitle(_translate("MainWindow", "Log"))
        self.ConnectionBox.setTitle(_translate("MainWindow", "Connection"))
        self.AutoDetectButton.setText(_translate("MainWindow", "AutoDetect"))
        self.manualConnectionBox.setText(_translate("MainWindow", "Manual"))
        self.laserPortLabel.setText(_translate("MainWindow", "Laser port:    COM"))
        self.shutterPortLabel.setText(_translate("MainWindow", "Shutter port: COM"))
        self.manualConnectButton.setText(_translate("MainWindow", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

